### PR TITLE
added missing hud_elements, fixes

### PR DESCRIPTION
**Pull request by EntranceJew**
simulation:

https://github.com/TTT-2/ttt2-octagonal-hud/assets/5711436/badf0bf5-3e0b-4952-a159-b66b4b1f730a

### CODE REVIEW

**Review by saibotk — APPROVED** [review]
LGTM

**Comment by TimGoll** [comment]
Did you test what happens when you have the pure_skin HUD selected? Because I see the octagonal skin for the killer info popup even though I have the pure_skin selected

**Comment by EntranceJew** [comment]
I hadn't had this happen yet, but as I was working on it I usually I had to run `Reset` in order for things to jump into their position, even when rescaling `pure_skin` but it could be from an oversight on my end.

**Comment by TimGoll** [comment]
> I hadn't had this happen yet, but as I was working on it I usually I had to run `Reset` in order for things to jump into their position, even when rescaling `pure_skin` but it could be from an oversight on my end.

Hm, I can reproduce this issue every time I try

**Pull request merged**
